import sqlite3

con = sqlite3.connect("../for_try-selenium/db.db")
cur = con.cursor()
#cur.execute("CREATE TABLE crawler(id INTEGER PRIMARY KEY AUTOINCREMENT, model TEXT, _date TEXT, title TEXT, link TEXT, price REAL, fee REAL, cost REAL, gb INTEGER, distributor TEXT)")
#cur.execute("DROP TABLE preorder")
#cur.execute("ALTER TABLE preorder ADD phone")
#cur.execute("INSERT INTO crawler(model, _date, title, link, price, fee, cost, gb, distributor) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?)", (, , , , , , , , ))
#cur.execute("UPDATE now_product SET num = ? WHERE id = ?", (50, 1))
#cur.execute("DELETE FROM crawler WHERE id > 0")
#con.commit()
#res = cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
#print(res.fetchone())
#print(res.fetchall())
#res = cur.execute("SELECT model, _date, title, cost, distributor FROM crawler")
res = cur.execute("SELECT id FROM crawler")
print(len(res.fetchall()))
cur.close()
con.close()
